### PR TITLE
E. coli 0.0.1

### PR DESCRIPTION
**Pull request by haowang-bioinfo**
- Initialize repo:
    - import iML1515 model from [BiGG](http://bigg.ucsd.edu/models/iML1515) database in 3 file formats: `xml`, `json`, and `mat`
    - update `README` from `standard-GEM` template with corresponding reference genome information
- Style:
    - add `yml` format model file and update meta data

### CODE REVIEW

**Review by mihai-sysbio — APPROVED** [review]
Looks good to me. Have you had a chance to look at or use the model in its YAML format?

**Comment by haowang-bioinfo** [comment]
will try it out

**Comment by mihai-sysbio** [comment]
> ~will try it out~ the YAML file cannot be loaded, I wonder how was it generated? @mihai-sysbio

It was written with the function in Human-GEM that exports YAML. Perhaps one should have used COBRApy instead.

**Comment by haowang-bioinfo** [comment]
> Perhaps one should have used COBRApy instead.

I support this plan, to which model files and code can be adjusted in follow-up releases to adapt.

> It was written with the function in Human-GEM that exports YAML. 

To assist smooth conversion without information loss and future integration into Met Atlas, Human-GEM `importYaml` function was [modified](https://github.com/SysBioChalmers/Human-GEM/pull/392) toward more generic use.

**Pull request merged**
